### ISSUE TITLE
Failed to locate: "CL.exe"

### ISSUE THREAD

**Issue by John-Constantine** [werkamsus/Lilith#1]
this project fails when i build it, gives 108 errors

some of the errors are  :  
![screenshot 2017-07-28 23 32 20](https://user-images.githubusercontent.com/26850770/28730289-195a4c96-73ed-11e7-8cf5-09e4717a616c.png)

**Comment by werkamsus** [comment]
This might be an error on your end. Do other projects compile properly?

**Comment by John-Constantine** [comment]
yes other project work perfectly, actually as soon as i build the project its been deleted by AV installed on my Windows 10

**Comment by werkamsus** [comment]
Well since this is in fact a program that can (can, not should!) be used maliciously, it might get pickend up by AV's. I suggest you disable yours temporarily or add an exception for Lilith.

**Comment by John-Constantine** [comment]
thanks for help;  is this behavior part of the design or hosted OS does it on its own

**Comment by werkamsus** [comment]
This behavior originates from the host OS, or the OS in General on which the Client is located. I have not looked into it's 'Detection Status', especially not recently. But when it started out there were no interferences with AV's. You can try for yourself and post about your findings here :)

**Comment by John-Constantine** [comment]
does it support ddns

**Comment by werkamsus** [comment]
Yes, you can just enter your ddns Hostname in the Settings.cpp file as the IP.

**Comment by John-Constantine** [comment]
i appreciate your instant help , i want to thank you especially for Lilith , this is a great project and i hope to see more functionality for this project, i will be happy to contribute to it , if you allow me to

**Comment by werkamsus** [comment]
Thank you, it's a pleasure :) Be sure to ask if any more questions or problems come up. I'd be very happy to see you contribute if you find the time to do so, thanks in advance!
