### ISSUE TITLE
NO-IP / Dynamic DNS doesnt work

### ISSUE THREAD

**Issue by ghost** [werkamsus/Lilith#12]
Hello,

connection with "127.0.0.1" and my PUBLIC IP works good. But with NO-IP / DynamicDNS "example.ddns.net" it doesnt work. No connection to the server. Please look at that issue so i can use DynamicDNS because my IP changes every 24h and DynamicDNS is very important. :-)

Also the server and client are not stable at all. I cant work or do other tasks while i am running the server or client. You already mentioned that .. and i am wondering how could i solve the problem for myself

Thanks in advance

Kinds regards

**Comment by werkamsus** [comment]
Thank you for pointing this out. I have received word from multiple people that dynamic DNS is not working as it should, and will fix this when I have some spare time on my hands.

**Comment by werkamsus** [comment]
Should be fixed now, please test :)
