### ISSUE TITLE
remoteControl cmd

### ISSUE THREAD

**Issue by MonMon3** [werkamsus/Lilith#14]
When executing a command. E.G. whoami i get this error.
![image](https://user-images.githubusercontent.com/19418035/42151980-e7a0d52a-7e32-11e8-9e7c-084b97b3d4ae.png)

cmdRedirect.cpp - CMD::writeCMD()

**Comment by werkamsus** [comment]
Have you tried running the program without the Debugger attached?
The access violation may occur within the pipe inter process communication, perhaps blocked by an AV.
Can you try switching the AV off and / or running the program elevated (as admin)?

Regards

**Comment by MonMon3** [comment]
When running it without the debugger it executes the command then dies.
I have indeed tried both of those two other things.

**Comment by werkamsus** [comment]
I have not heard of this before and believe it is an error on your end. I hope you get it resolved, however I'm afraid I cannot help you.
