### ISSUE TITLE
[Info] CreateThread Function Handling Issues

### ISSUE THREAD

**Issue by gy741** [werkamsus/Lilith#16]
Hello.

In the area where the CreateThread function is used, there appears to be no appropriate exception if the Return value occurs Null.

What do you think?

```
client.cpp:165
general.cpp:303
Server/server.cpp:37
Server/server.cpp:42
Server/server.cpp:334
```

https://github.com/werkamsus/Lilith/blob/1cd9afe8f3d42d258c1493651cb995c20b306622/Server/server.cpp#L37

Thanks.

**Comment by werkamsus** [comment]
Fixed by @czs108 in 76b5511c93eab1d6de3c79934d937392d8c68644
