### ISSUE TITLE
Web interface support

### ISSUE THREAD

**Issue by nullybyte** [werkamsus/Lilith#20]
i am available for the web interface development(PHP) and a good god view mode.

**Comment by werkamsus** [comment]
What framework are you thinking of? I'm pretty well versed in laravel and could assist from time to time. But if you prefer something else, just give it a shot. Super happy that you want to build a GUI for Lilith! 😄

**Comment by duanyiemo3** [comment]
Great idea. Where should I find this project?

**Comment by werkamsus** [comment]
You can find it here: https://laravel.com/

There are some great tutorials to get you started, laracasts is the best in my opinion: https://laracasts.com/

**Comment by duanyiemo3** [comment]
If you have gui source code will be great。LOL
