### ISSUE TITLE
What is winlive.exe ? what is it used for in Lilith

### ISSUE THREAD

**Issue by John-Constantine** [werkamsus/Lilith#3]
hi

i was looking at the files generated when we build Liltith , and i came across a file named "winlive.exe" , i am curious what is this file used for , what class is generating it , etc etc, i tried to google "winlive.exe" but it smells like a malicious file.

thanks.

**Comment by werkamsus** [comment]
It's the client itself. This is the file you need to execute in order to connect to the server. I seemed to have renamed it at some point, will change that.

**Comment by John-Constantine** [comment]
i am not sure if its client as , when i build the solution, i get 3 files, Server.exe, Lilith.exe and WinLive.exe. thanks for replying

**Comment by werkamsus** [comment]
Well that shouldn't happen, and it doesn't on my end. Does that happen on
every build?

**Comment by John-Constantine** [comment]
on every build with release mode
