### ISSUE TITLE
Marked as "Trojan:Win32/Azden.A!cl"

### ISSUE THREAD

**Issue by John-Constantine** [werkamsus/Lilith#5]
hi, i am actually very much impressed by and in Lilith that's why i have been working on it from many days

i am getting unwanted behavior and warning , i am now not even able to build it, 

**NOTE:**

i haven't added any code to it yet i was just inspecting and trying it. i just want to make sure to work on some RAT or similar application that isn't going to end up in some antivirus detection list.

can you suggest something that can help in minimizing the suspeciuos behavior 

thanks alot

**Comment by werkamsus** [comment]
Well that happens with each and every single rat that people publish. Look
at quasarRAT, that's also flagged as a Trojan. Apparently someone uploaded
it to virustotal or a similar website that then indexed it as malicious.
